apiVersion: batch/v1
kind: Job
metadata:
  name: nilay-pdfocr
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-A100-SXM4-80GB
                      - NVIDIA-A100-80GB-PCIe
                      - NVIDIA-A100-80GB-PCIe
                      - NVIDIA-GeForce-RTX-3090
                      - NVIDIA-GeForce-RTX-4090
      imagePullSecrets:
        - name: nilay-ghcr-key
      containers:
        - name: converter
          image: ghcr.io/offendo/pdfocr:latest
          # command: ["/bin/bash"]
          # args:
          #   ["-c", "nougat --checkpoint nougat-base/ -o /volume/pdfocr/per-page/ /volume/pdfocr/pdfs/"]
          command: ["python"]
          args:
            [
              "random_pages.py", 
              "--pdf_dir",
              "/volume/pdfocr/pdfs/",
              "--output_dir",
              "/volume/pdfocr/per-page/",
              "--n_books",
              "50",
              "--pages",
              "100"
            ]
          workingDir: /app
          volumeMounts:
            - name: nilay-data-volume-rwm-central
              mountPath: /volume
            - name: api-tokens
              mountPath: /etc/api-tokens
          resources:
            limits:
              memory: 64Gi
              cpu: 2
              nvidia.com/gpu: 1
              ephemeral-storage: 50Gi
            requests:
              memory: 64Gi
              cpu: 2
              nvidia.com/gpu: 1
              ephemeral-storage: 50Gi
      initContainers:
        - name: chmod
          image: alpine:latest
          command: ["chmod", "-R", "a+rw", "/volume"]
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: nilay-data-volume-rwm-central
              mountPath: /volume
      securityContext:
        fsGroup: 101
      volumes:
        - name: nilay-data-volume-rwm-central
          persistentVolumeClaim:
            claimName: nilay-data-volume-rwm-central
        - name: api-tokens
          secret:
            defaultMode: 0400
            secretName: nilay-api-tokens
      restartPolicy: Never
  backoffLimit: 0
