apiVersion: v1
kind: Pod
metadata:
  name: nilay-pdfocr-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-A100-SXM4-80GB
                  - NVIDIA-A100-80GB-PCIe
                  - NVIDIA-A100-80GB-PCIe
                  - NVIDIA-GeForce-RTX-3090
                  - NVIDIA-GeForce-RTX-4090
  imagePullSecrets:
    - name: nilay-ghcr-key
  containers:
    - name: converter
      image: ghcr.io/offendo/pdfocr:latest
      # command: ["/bin/bash"]
      # args:
      #   ["-c", "nougat --checkpoint nougat-base/ -o /volume/pdfocr/per-page/ /volume/pdfocr/pdfs/"]
      command: ["sleep", "21600"]
      workingDir: /app
      volumeMounts:
        - name: nilay-data-volume-rwm-central
          mountPath: /volume
        - name: api-tokens
          mountPath: /etc/api-tokens
      resources:
        limits:
          memory: 32Gi
          cpu: 1
          nvidia.com/gpu: 1
          ephemeral-storage: 25Gi
        requests:
          memory: 32Gi
          cpu: 1
          nvidia.com/gpu: 1
          ephemeral-storage: 25Gi
  initContainers:
    - name: chmod
      image: alpine:latest
      command: ["chmod", "-R", "a+rw", "/volume"]
      resources:
        limits:
          memory: 4Gi
          cpu: 1
        requests:
          memory: 4Gi
          cpu: 1
      volumeMounts:
        - name: nilay-data-volume-rwm-central
          mountPath: /volume
  securityContext:
    fsGroup: 101
  volumes:
    - name: nilay-data-volume-rwm-central
      persistentVolumeClaim:
        claimName: nilay-data-volume-rwm-central
    - name: api-tokens
      secret:
        defaultMode: 0400
        secretName: nilay-api-tokens
  restartPolicy: Never
