apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nilay-data-volume-rwm-central
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

