apiVersion: v1
kind: Pod
metadata: 
  name: nilay-pod
spec:
  containers:
    - name: pod
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      workingDir: /
      volumeMounts:
        - name: nilay-data-volume-rwm-central
          mountPath: /volume
      resources:
        limits:
          memory: 16Gi
          cpu: 1
          ephemeral-storage: 50Gi
        requests:
          memory: 16Gi
          cpu: 1
          ephemeral-storage: 50Gi
  securityContext:
    fsGroup: 101
  volumes:
    - name: nilay-data-volume-rwm-central
      persistentVolumeClaim:
        claimName: nilay-data-volume-rwm-central
  restartPolicy: Never
